name: Game Website Monitor

on:
  schedule:
    - cron: '*/10 * * * *'  # 每10分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests feedparser python-dateutil PyGithub
    
    - name: Run monitor script
      run: python main.py
    
    - name: Create Issues for new pages
      env:
        LOG_TOKEN: ${{ secrets.LOG_TOKEN }}
      run: python create_issues.py